[package]
name = "kagome-client"
version = "0.1.0"
edition = "2021"

[dependencies]
grammar-lib = { path = "../grammar-lib" }
reqwest = { version = "0.12", features = ["blocking", "json"] }
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
