[package]
name = "anime-search"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
regex = "1.10.5"
rusqlite = { version = "0.32.1", features = ["bundled"] }
walkdir = "2"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.12.0"