[package]
name = "grammar-lib"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "grammar-cli"
path = "src/bin/grammar-cli.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
kagome-client = { path = "../kagome-client" }
